# Generated by Django 5.2.17 on 2026-08-08 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hostel", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MealSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_date", models.DateField()),
                (
                    "meal_type",
                    models.CharField(
                        choices=[
                            ("breakfast", "Breakfast"),
                            ("lunch", "Lunch"),
                            ("dinner", "Dinner"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "location",
                    models.CharField(default="Main dining hall", max_length=80),
                ),
                ("menu_name", models.CharField(max_length=160)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("open", "Open"),
                            ("closed", "Closed"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("forecast_diners", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "prepared_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "served_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "waste_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("unit", models.CharField(default="portions", max_length=16)),
                ("opened_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "hostel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="meal_sessions",
                        to="hostel.hostel",
                    ),
                ),
            ],
            options={
                "ordering": ["-service_date", "meal_type"],
                "indexes": [
                    models.Index(
                        fields=["hostel", "service_date"],
                        name="meals_meals_hostel__99d127_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("hostel", "service_date", "meal_type", "location"),
                        name="unique_meal_session_natural_key",
                    )
                ],
            },
        ),
    ]
