# Generated by Django 5.2.17 on 2026-08-08 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hostel", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RosterImport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("digest", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("previewed", "Previewed"),
                            ("committed", "Committed"),
                            ("failed", "Failed"),
                        ],
                        default="previewed",
                        max_length=16,
                    ),
                ),
                ("accepted_rows", models.PositiveIntegerField(default=0)),
                ("rejected_rows", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "hostel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="hostel.hostel"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("hostel", "digest"),
                        name="unique_roster_digest_per_hostel",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.CharField(max_length=64)),
                ("full_name", models.CharField(max_length=160)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("room_number", models.CharField(blank=True, max_length=32)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "hostel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="students",
                        to="hostel.hostel",
                    ),
                ),
            ],
            options={
                "ordering": ["full_name"],
                "indexes": [
                    models.Index(
                        fields=["hostel", "status", "full_name"],
                        name="students_st_hostel__410618_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("hostel", "external_id"),
                        name="unique_student_external_id_per_hostel",
                    )
                ],
            },
        ),
    ]
